# manual-test-run.yml

name: Manual Test Run

# این ورک‌فلو فقط به صورت دستی فعال می‌شود
on:
  workflow_dispatch:

jobs:
  run-full-test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # در اینجا، ما اسکریپت را با یک تسک جدید به نام TEST_ALL اجرا می‌کنیم
      - name: Run Full Test Sequence
        run: node main.js TEST_ALL
        env:
          PRIVATE_KEY: ${{ secrets.YOUR_PRIVATE_KEY }}
